version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/vertx-web-graphql"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "com.graphql-java:graphql-java"
      - dependency-name: "org.testcontainers:*"

  - package-ecosystem: "maven"
    directory: "/vertx-web-graphql"
    target-branch: 4.x
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "com.graphql-java:graphql-java"
      - dependency-name: "org.testcontainers:*"
    ignore:
      - dependency-name: "com.graphql-java:graphql-java"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/vertx-web-graphql"
    target-branch: "5.0"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "com.graphql-java:graphql-java"
      - dependency-name: "org.testcontainers:*"
    ignore:
      - dependency-name: "com.graphql-java:graphql-java"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/vertx-web-graphql/vertx-web-graphiql"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 10
