language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
jobs:
  include:
    - stage: test
      name: "OpenJDK 8"
      jdk: openjdk8
      script: mvn -q clean verify -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -B
    - name: "Apollo Link tests"
      jdk: openjdk8
      before_script:
        - cd vertx-web-graphql
        - mvn exec:java -Dexec.mainClass=io.vertx.ext.web.handler.graphql.ApolloTestsServer -Dexec.classpathScope=test > ${HOME}/ApolloTestsServer.log 2>&1 &
        - echo $! > ${HOME}/ApolloTestsServer.pid
        - ( tail -f ${HOME}/ApolloTestsServer.log & ) | grep -q "Apollo tests server started"
      script:
        - cd tests/apollo
        - npm install
        - npm run test
      after_failure: cat ${HOME}/ApolloTestsServer.log
      after_script: cat ${HOME}/ApolloTestsServer.pid | xargs kill -9
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      jdk: openjdk8
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script:
        - cd vertx-web-graphql/vertx-web-graphiql
        - npm run build
        - cd build
        - cp index.html ../../src/main/resources/io/vertx/ext/web/handler/graphiql
        - find static -name "*.js"  -exec cp --parents {} ../../src/main/resources/io/vertx/ext/web/handler/graphiql \;
        - find static -name "*.css"  -exec cp --parents {} ../../src/main/resources/io/vertx/ext/web/handler/graphiql \;
        - cd ../../..
        - bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - secure: "Q9QVThuDW0VF6OAcaeFbdOZrK8DBoaDw4GVqDukbgPWyjoJN/KTifxFYIJGDsYva5gZp9OKyeTe3cYC0MBlX2SMlJbU83HkApl3EKmM6QGgFVGbRZAjX0LVX5sGhlqfcyjiYedORlTLeEuJfbiYoPoEfQ1dR8cEPSCdInA+mgb0="
    on_success: always
    on_failure: always
